name: my-workflow
on: workflow_dispatch #manual trigger
jobs: #must be plural
  echo: #indented - belongs to parent, name doesn't matter
    runs-on: ubuntu-20.04 #reserved word, check runners on github docs
    steps: 
      - name: Say hello
        run: echo "Hello World!!!"
      - name: Say goodbye
        run: echo "Goodbye World!!!"
    
