name: jobs in series 
on: workflow_dispatch
jobs:
  say-hello:
    runs-on: ubuntu-20.04
    steps: 
      - name: Say hello
        run: echo "Hello World!!!"
      - name: sleep 5 seconds
        run: sleep 5
  say-goodbye:
    runs-on: ubuntu-20.04
    needs: say-hello
    steps: 
      - name: Say goodbye
        run: echo "Goodbye World!!!"
      - name: sleep 5 seconds
        run: sleep 5
