name: push-to-feature
on:
  push:
    branches: [ "feature" ]
jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - name: Push msg
        run: echo "Some text output on push to feature branch"

