name: push-to-feature
on:
  push:
    branches: [ "feature" ]
jobs:
  echo:
    runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          run: echo "Some text output on push to feature branch"
